name: Build Android APK

on:
  push:
    branches: [ "main" ] # This workflow runs every time you push to the main branch

jobs:
  build-android:
    runs-on: ubuntu-latest # Use a fresh Ubuntu machine for the build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use the specialized Kivy Buildozer action
      # This action handles setting up Java, Python, Buildozer,
      # Android SDK, NDK, and running the buildozer commands.
      - name: Build Android APK with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          # The command to execute buildozer.
          # The action will automatically find buildozer.spec in the 'workdir'.
          command: 'buildozer android debug'
          # The root of your repository, usually '.'
          repository_root: '.'
          # The working directory where your buildozer.spec file is located.
          # Assuming it's in the root of your repository.
          workdir: '.'
          # You can specify a particular buildozer version, or 'stable' for the latest stable.
          buildozer_version: 'stable'

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-survey-apk
          path: bin/*.apk # The APK will be generated in the 'bin' directory relative to workdir
