name: Build Android APK

on:
  push:
    branches: [ "main" ] # This workflow runs every time you push to the main branch

jobs:
  build-android:
    runs-on: ubuntu-latest # Use a fresh Ubuntu machine for the build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Install Python and Buildozer
        run: |
          pip install --upgrade cython
          pip install --upgrade buildozer

      - name: Build the APK with Buildozer
        run: |
          # 1. Update/download the Buildozer-managed Android SDK
          buildozer android update

          # 2. Accept the licenses for the SDK that Buildozer just downloaded
          yes | /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

          # 3. Now, build the APK with all dependencies and licenses in place
          buildozer android debug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-survey-apk
          path: bin/*.apk
