name: Build Android APK

on:
  push:
    branches: [ "main" ] # This workflow runs every time you push to the main branch

jobs:
  build-android:
    runs-on: ubuntu-latest # Use a fresh Ubuntu machine for the build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use the specialized Kivy Buildozer action
      # This action handles setting up Java, Python, Buildozer,
      # Android SDK, NDK, and running the buildozer commands.
      - name: Build Android APK with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1 # Corrected action name
        with:
          # The path to your buildozer.spec file (usually in the root of your repo)
          buildozer_spec: 'buildozer.spec'
          # You can specify the build profile, e.g., 'debug' or 'release'
          # build_profile: 'debug' # Default is 'debug' if not specified

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-survey-apk
          path: bin/*.apk # The APK will be generated in the 'bin' directory
