name: Build Android APK

on:
  push:
    branches: [ "main" ] # This workflow runs every time you push to the main branch

jobs:
  build-android:
    runs-on: ubuntu-latest # Use a fresh Ubuntu machine for the build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Java
        uses: actions/setup-java@v4 # Updated to v4
        with:
          distribution: 'temurin' # A popular OpenJDK distribution
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # CORRECTED: Removed libtinfo5 as it's deprecated in newer Ubuntu images
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Install Python and Buildozer
        run: |
          pip install --upgrade cython
          pip install --upgrade buildozer

      - name: Build the APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4 # CORRECTED: Updated from v3 to v4
        with:
          name: smart-survey-apk # The name of the downloadable file
          path: bin/*.apk # The location of the built APK
